import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Adam Silvia Consulting",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-segoe antialiased">
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
